### ISSUE TITLE
Package is not published

### ISSUE THREAD

**Issue by endel** [kawanet/from-xml#1]
Hey @kawanet, is your library ready to use? It doesn't look to be published on NPM yet. Cheers!

**Comment by endel** [comment]
`to-xml` package is not published as well

**Comment by kawanet** [comment]
I'm still working on it. It needs to support three more functionalities: XML declaration <?xml...?>, comments <!...> and CDATA section <![CDATA[...]]> before published on NPM. I hope it'd not take so long. Thanks, anyway!

**Comment by kawanet** [comment]
Both published.
- https://www.npmjs.com/package/from-xml
- https://www.npmjs.com/package/to-xml
