### ISSUE TITLE
compilation issue with webpack

### ISSUE THREAD

**Issue by bouteaupo-bpk** [kawanet/from-xml#11]
Since version 0.1.10, I have a compilation issue with the lib : `Module not found: Error: Default condition should be last one
`

I think the cause is the package.json from this commit https://github.com/kawanet/from-xml/commit/b4884c47050e1a0bebd732ddf9b757797652a723

I think `default` should be after `types`, it fixed the issue on my env

**Comment by kawanet** [comment]
@bpkpierreolivierb thanks you for telling me the hack.
I've tested on TypeScript v5 but not with Webpack.
Could you please confirm the commit 61ce4abb336ddb8de71812d6fbfc0362b94cef56 works on your env?

**Comment by kawanet** [comment]
confirmed. I'll publish it as 0.1.11 then.

```
Module not found: Error: Default condition should be last one
```
