### ISSUE TITLE
Children with the same name are replaced

### ISSUE THREAD

**Issue by endel** [kawanet/from-xml#2]
I think this is an expected behaviour by design, just wanted to let you know that the following scenario wouldn't work:

``` xml
<items>
    <item .../>
    <item .../>
    <item .../>
</items>
```

It gets parsed with a single `item` as a child. (`{ items: { item: ... } }`)

Feel free to just close this issue, as I think it's not an issue of your approach, but the XML's.

Cheers

**Comment by kawanet** [comment]
supported.

https://github.com/kawanet/from-xml#multiple-child-nodes

**Comment by endel** [comment]
Thanks! For some reason it wasn't working when I tested.
Your implementation is way faster than [`xml-parser`](https://www.npmjs.com/package/xml-parser), great job!
