### ISSUE TITLE
Element order not preserved

### ISSUE THREAD

**Issue by rodinhart** [kawanet/from-xml#3]
For example:

```xml
<svg>
  <rect width="10" height="10" />
  <text>On top</text>
</svg>
```

is translated to:

```js
{
    "svg": {
        "rect": {
            "@width": "10",
            "@height": "10"
        },
        "text": "On top"
    }
}
```

which does not guarantee the order of `rect` and `text`.

**Comment by kawanet** [comment]
Correct. The simple module does not handle the order. Thanks for the report!

**Comment by rodinhart** [comment]
Thanks for the response. I shall use JSONML instead.
