### ISSUE TITLE
Question/Help with reviver

### ISSUE THREAD

**Issue by a1730** [kawanet/from-xml#8]
Hi!
First, Thank you very much  for this package.
I am migrating my old code base from your  XML.ObjTree library which has been serving us for many years.
XML.ObjTree has a force_array property that we love. I, unfortunately, could not come up with a reviver to replicate that functionality in from-xml.

Do you have any pointers for us?
Thank you very much.

**Comment by kawanet** [comment]
@a1730 
Thank you for your comment.
`from-xml` is forcused on simpleness and lost some features from `XML.ObjTree` including `force_array` etc.
Instead, I often write a code like below:

```js
const xml = `
<foo>
    <bar>1</bar>
    <bar>2</bar>
</foo>
`;
const data = fromXML(xml);
let {bar} = data.foo;
if (!Array.isArray(bar) && bar != null) bar = [bar];
```

`reviver` looks not enough powerfull to implement `force_array` unfortunately. Below doesn't work.

```js
const forceArray = {bar: 1};

fromXML(xml, (key, val) => (forceArray[key] && !Array.isArray(val) && val != null) ? [val] : val);
```

**Comment by a1730** [comment]
Thank you for the swift response.

The key insight is that reviver works on values, not keys.
So, I attempted a fix ... My changes are minimal. I hope that you will review and bring the changes to your coding standard, and release a version with this feature.

1. Added a set to track forced_array elements,
```const FORCED_ARRAY = new Set()```
2. added, and exported, a function to set forced array,
```
export function setForcedArray(elems = "") {
  elems.split(',').forEach(elem => FORCED_ARRAY.add((new String(elem).trim())))
}
```
3. patched addObject to recognize forced_arrays.
The hard work is in addObject **Please review**
```
function addObject(object, key, val) {
    if ("undefined" === typeof val) return;
    const prev = object[key];
    if (prev instanceof Array) {
      prev.push(val);
    } else if (key in object) {
      object[key] = [prev, val];
    } else if (FORCED_ARRAY.has(key)) {
      object[key] = [val];
    } else {
      object[key] = val;
    }
  }
```
Using a modified version with above patches on 
```js
const xml=`
<?xml version="1.0" encoding="UTF-8"?>
<family name="Kawasaki">
    <father>Yasuhisa</father>
    <mother>Chizuko</mother>
    <children>
        <girl>Shiori</girl>
        <boy>Yusuke</boy>
        <boy>Kairi</boy>
    </children>
</family>`

setForcedArray("father,girl")
const data = fromXML(xml)
```
Our result is
```json
{
  "?": "xml version=\"1.0\" encoding=\"UTF-8\"",
  "family": {
    "@name": "Kawasaki",
    "father": [
      "Yasuhisa"
    ],
    "mother": "Chizuko",
    "children": {
      "girl": [
        "Shiori"
      ],
      "boy": [
        "Yusuke",
        "Kairi"
      ]
    }
  }
}
```

I would have created a PR but I don't do Git. Apologies.

**Comment by a1730** [comment]
I am sorry @kawanet  that I do not do Git.

**Comment by a1730** [comment]
Our little patch worker for us. Thank you very much for the hint.
